server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  # 数据库配置
  datasource:
    # Hikari连接池
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/base-project?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true
    username: root
    password: 123456
    hikari:
      # 最大连接池数量
      maximum-pool-size: 20
      # 最小空闲线程数量
      minimum-idle: 10
      # 配置获取连接等待超时的时间
      connectionTimeout: 30000
      # 校验超时时间
      validationTimeout: 5000
      # 空闲连接存活最大时间，默认10分钟
      idleTimeout: 600000
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
      maxLifetime: 1800000
      # 连接测试query（配置检测连接是否有效）
      connectionTestQuery: SELECT 1
      # 多久检查一次连接的活性
      keepaliveTime: 30000
  data:
    redis:
      # Redis数据库索引（默认为0）
      database: 0
      host: localhost
      port: 6379
      password:
      lettuce:
        pool:
          # 连接池最大连接数（使用负值表示没有限制） 默认 8
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
          max-wait: -1
          # 连接池中的最大空闲连接 默认 8
          max-idle: 8
          # 连接池中的最小空闲连接 默认 0
          min-idle: 0
  jpa:
    # 避免启动时在日志中会出现警告
    open-in-view: false
    hibernate:
      ddl-auto: none
    # 显示sql语句
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        # 格式化sql语句
        format_sql: true
  flyway:
    # 是否启用flyway
    enabled: true
    # 编码格式，默认UTF-8
    encoding: UTF-8
    # 迁移sql脚本文件存放路径，默认db/migration
    locations: classpath:db/mysql
    # 迁移sql脚本文件名称的前缀，默认V
    sql-migration-prefix: V
    # 迁移sql脚本文件名称的分隔符，默认2个下划线__
    sql-migration-separator: __
    # 迁移sql脚本文件名称的后缀
    sql-migration-suffixes: .sql
    # 迁移时是否进行校验，默认true
    validate-on-migrate: true
    # 当迁移发现数据库非空且存在没有元数据的表时，自动执行基准迁移，新建schema_version表
    baseline-on-migrate: true

# jwt 配置
jwt:
  # 加密盐
  secret: luckykuang
  # access_token过期时间(ms)
  access-token-expiration-date: 300000
  # refresh_token过期时间(ms)
  refresh-token-expiration-date: 600000

# 验证码配置
easy:
  captcha:
    # 是否开启(暂未开发)
    # enable: true
    # 验证码类型: arithmetic-算术
    type: arithmetic
    # 验证码有效时间(单位：秒)
    ttl: 120

logging:
  level:
    com.luckykuang: info
    # 用于日志监控
    com.luckykuang.auth.controller: trace
    # 用于查看传入的参数
    # 基本类型绑定
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    # 枚举类型绑定
    org.hibernate.metamodel.model.convert.internal.NamedEnumValueConverter: trace

# spring doc 配置
springdoc:
  api-docs:
    # true - 开启API文档功能，false - 关闭API文档功能
    enabled: true
  swagger-ui:
    enabled: true
    # “list”（仅展开标记）、“full”（展开标记和操作）、“none”（不展开任何内容）。
    docExpansion: none
    # “alpha”（按路径字母数字排序），“method”（按HTTP方法排序）
    operationsSorter: method
  # GET请求下，让swagger将DTO封装入参解析成form参数
  default-flat-param-object: true
knife4j:
  # 开启增强功能
  enable: true
  setting:
    language: zh_cn