server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    url: jdbc:mysql://1.12.248.106:3308/demo22?characterEncoding=utf-8&useSSL=false
    username: root
    password: Hex.863731274
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    # 显示sql语句
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        # 格式化sql语句
        format_sql: true
logging:
  level:
    # 用于查看传入的参数
    # 基本类型绑定
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    # 枚举类型绑定
    org.hibernate.metamodel.model.convert.internal.NamedEnumValueConverter: trace