server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/base-project?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      # Redis数据库索引（默认为0）
      database: 0
      host: localhost
      port: 6379
      password: 123456
      lettuce:
        pool:
          # 连接池最大连接数（使用负值表示没有限制） 默认 8
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
          max-wait: -1
          # 连接池中的最大空闲连接 默认 8
          max-idle: 8
          # 连接池中的最小空闲连接 默认 0
          min-idle: 0
  jpa:
    # 避免启动时在日志中会出现警告
    open-in-view: false
    hibernate:
      ddl-auto: none
    # 显示sql语句
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        # 格式化sql语句
        format_sql: true

## App Properties
app:
  # jwt 加密盐
  jwt-secret: luckykuang
  # jwt 过期时间(ms)
  jwt-expiration:
    access-token-milliseconds: 300000
    refresh-token-milliseconds: 600000
  # 跨域url配置，配置多个用英文逗号分割
  cors-urls: http://localhost:8080
  # 跨域方法配置，配置多个用英文逗号分割
  cors-methods: GET,POST,PUT,DELETE

logging:
  level:
    com.luckykuang: info

# spring doc 配置
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
knife4j:
  enable: true
  production: true